### PR TITLE
fix: app deprecations

### PR DESCRIPTION
**Pull request by tabathadelane**
Handle NR1 deprecations. 

closes https://github.com/newrelic/nr1-catalog/issues/324

### CODE REVIEW

**Comment by aswanson-nr** [comment]
We had to do a bit of object massaging to get things into the same state they were before these changes, please let us know if there are any issues with this approach!

**Comment by aswanson-nr** [comment]
FYI I pinged @JimHagan about giving us a review on this before merging.

**Comment by JimHagan** [comment]
@aswanson-nr our partner's development @rommelwigilabs @rsamanez will be reviewing the code for any unforseen impacts.

**Comment by aswanson-nr** [comment]
For reference: [the deprecations](https://developer.newrelic.com/build-apps/nr1-deprecations/)

**Review by rsamanez — APPROVED** [review]

**Comment by JimHagan** [comment]
@aswanson-nr Rommel from Wigi has gone through and added a few more commits.  Would you or someone from your team be able to look at this commits?  I believe we are okay to merge this based on Romme's most recent revision, but it would be great to have consensus between you , me and him.

Once we are merged.  I would like to create a release and update it in the catalog if that's okay since we like to try to keep the deployed Pathpoint up to date with the current state of `main`

**Review by JimHagan — APPROVED** [review]

**Comment by rsamanez** [comment]
there is a HIGH vulnerability in the version of the libraries, to solve it it is necessary to run this command to update the libraries package:
```
npm audit fix
```
I think we can do it before to merge the code

**Pull request merged**
