### PR TITLE
Feature/gui editor

### PR DESCRIPTION
**Pull request by rsamanez**
In this Update:

- Adding Stages GUI Editor
- Adding Steps GUI Editor
- Adding Touchpoints GUI Editor

### CODE REVIEW

**Comment by rsamanez** [comment]
We found some Bugs in this Update, DO NOT PROCEED with the Merge Request

**Comment by rsamanez** [comment]
BUGS Fixed, The app is ready to Merge

**Comment by JimHagan** [comment]
I am in the process of reviewing this now.

@rsamanez

**Review by JimHagan — APPROVED** [review]
I approve this PR

**Pull request merged**
